import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const ListingView: NextPage = () => {
  const router = useRouter();
  const listing = api.listings.fetchListing.useQuery(
    {
      listingId: router.query.id as string,
    },
    { enabled: !!router.query.id }
  );

  if (!listing.data) {
    return (
      <div className="flex h-screen items-center justify-center">
        <div className="text-center">Unable to find the listing...</div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-8 flex flex-col items-center">
        <h1 className="mb-4 text-2xl font-bold">{listing.data.name}</h1>
        <p className="mb-4 text-xl">{listing.data.description}</p>
        <button className="inline-flex items-center rounded-lg bg-[#e4ff1b] px-3 py-2 text-center text-sm font-medium text-[#131019] hover:bg-[#c9e209] focus:outline-none focus:ring-4">
          Buy - ${listing.data.price.toString()}
          <svg
            aria-hidden="true"
            className="-mr-1 ml-2 h-4 w-4"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
      </main>
    </>
  );
};

export default ListingView;
