import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const ListingView: NextPage = () => {
  const router = useRouter();
  const listing = api.listings.fetchListing.useQuery(
    {
      listingId: router.query.id as string,
    },
    { enabled: !!router.query.id }
  );
  if (!listing.data) return;
  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <h1 className="mt-3 text-2xl">{listing.data.name}</h1>
        <p className="mt-3 text-xl">{listing.data.description}</p>
      </main>
    </>
  );
};

export default ListingView;
