/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import { useForm, type SubmitHandler } from "react-hook-form";
import { api } from "../utils/api";

type SellItemForm = {
  name: string;
  description: string;
  price: number;
};

const SellAnItem: NextPage = () => {
  const createListing = api.listings.create.useMutation();

  const { register, handleSubmit } = useForm<SellItemForm>();
  const onSubmit: SubmitHandler<SellItemForm> = (formData) => {
    createListing.mutateAsync(formData);
  };
  return (
    <>
      <Head>
        <title>Koi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1>Sell an item</h1>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="mb-6 grid gap-6 md:grid-cols-2">
              <div>
                <label
                  htmlFor="item_name"
                  className="mb-2 block text-sm font-medium"
                >
                  Item name
                </label>
                <input
                  id="item_name"
                  className="block w-full rounded-lg border border-transparent bg-[#47424f] p-2.5 text-sm focus:border-blue-500 active:border-blue-500"
                  {...register("name", { required: true })}
                />
              </div>
              <div>
                <label
                  htmlFor="description"
                  className="mb-2 block text-sm font-medium"
                >
                  Description
                </label>
                <input
                  id="description"
                  className="block w-full rounded-lg border border-transparent bg-[#47424f] p-2.5 text-sm focus:border-blue-500 active:border-blue-500"
                  {...register("description", { required: true })}
                />
              </div>
              <div>
                <label
                  htmlFor="price"
                  className="mb-2 block text-sm font-medium"
                >
                  Price
                </label>
                <input
                  type="number"
                  step={"0.01"}
                  id="price"
                  className="block w-full rounded-lg border border-transparent bg-[#47424f] p-2.5 text-sm focus:border-blue-500 active:border-blue-500"
                  {...register("price", { required: true })}
                />
              </div>
            </div>
            <button
              type="submit"
              className="w-full rounded-lg bg-[#1a34d3] px-5 py-2.5 text-center text-sm font-medium sm:w-auto"
            >
              Create
            </button>
          </form>
        </div>
      </main>
    </>
  );
};

export default SellAnItem;
